"""
Management command to seed all 70+ courses.
Run: python manage.py seed_courses
"""
from django.core.management.base import BaseCommand
from apps.courses.models import Category, Course, CurriculumModule, Mentor

CATEGORIES = [
    {"name": "AI & Machine Learning", "slug": "ai-ml", "icon": "FaBrain", "color": "#461E96",
     "description": "Master artificial intelligence, machine learning, deep learning, NLP, computer vision, generative AI, agentic AI, and more.",
     "is_featured": True, "order": 1},
    {"name": "SAP Modules", "slug": "sap", "icon": "FaCogs", "color": "#00B4E6",
     "description": "Comprehensive SAP training covering ERP, S/4HANA, Commerce Cloud, Spartacus, CPI, FICO, MM, SD, ABAP, and UI5/Fiori.",
     "is_featured": True, "order": 2},
    {"name": "Programming Languages", "slug": "programming", "icon": "FaCode", "color": "#E6008C",
     "description": "Learn in-demand programming languages: Python, Java, PHP, .NET, Node.js, Go, Rust, and full-stack frameworks.",
     "is_featured": True, "order": 3},
    {"name": "Cloud Computing", "slug": "cloud", "icon": "FaCloud", "color": "#00DC8C",
     "description": "Get cloud-certified: AWS, Azure, GCP, Docker, Kubernetes, Terraform, and DevOps practices.",
     "is_featured": True, "order": 4},
    {"name": "Cybersecurity", "slug": "cybersecurity", "icon": "FaShieldAlt", "color": "#735CCC",
     "description": "Learn ethical hacking, penetration testing, SOC analysis, and cybersecurity certifications.",
     "is_featured": True, "order": 5},
    {"name": "Data Engineering", "slug": "data-engineering", "icon": "FaDatabase", "color": "#80DEFF",
     "description": "Master data pipelines, big data, Spark, Hadoop, Kafka, data warehousing, and analytics.",
     "is_featured": True, "order": 6},
    {"name": "Web & Frontend", "slug": "web-frontend", "icon": "FaGlobe", "color": "#FD6CB0",
     "description": "Build modern web applications with Angular, React, Vue.js, and full-stack development.",
     "is_featured": True, "order": 7},
    {"name": "DevOps & QA", "slug": "devops-qa", "icon": "FaServer", "color": "#8AF6BB",
     "description": "CI/CD, automation testing, Selenium, performance testing, and DevOps engineering.",
     "is_featured": True, "order": 8},
    {"name": "Digital Marketing", "slug": "digital-marketing", "icon": "FaBullhorn", "color": "#FED0E2",
     "description": "SEO, SEM, social media marketing, content marketing, and analytics.",
     "is_featured": True, "order": 9},
]

COURSES = [
    # AI & ML
    {"title": "Artificial Intelligence Fundamentals", "slug": "artificial-intelligence-fundamentals",
     "category_slug": "ai-ml", "short_description": "Complete introduction to AI concepts, history, applications, and future trends.",
     "level": "beginner", "duration_hours": 40, "duration_weeks": 6, "price": 15000, "discount_price": 11999,
     "is_featured": True, "is_trending": True,
     "highlights": ["Understanding AI, ML, DL differences", "AI applications across industries", "Introduction to neural networks", "AI ethics and responsible AI", "Hands-on AI tools", "Career roadmap in AI"],
     "tools_covered": ["Python", "Jupyter Notebook", "Google Colab", "TensorFlow Playground"],
     "curriculum": [
         {"title": "Introduction to Artificial Intelligence", "topics": ["What is AI?", "History of AI", "Types of AI", "AI vs ML vs DL", "AI in daily life"], "hours": 4},
         {"title": "Mathematical Foundations", "topics": ["Linear Algebra", "Probability & Statistics", "Calculus fundamentals", "Optimization"], "hours": 6},
         {"title": "Machine Learning Basics", "topics": ["Supervised vs Unsupervised", "Classification & Regression", "Decision Trees", "KNN", "Model evaluation"], "hours": 8},
         {"title": "Neural Networks Introduction", "topics": ["Perceptrons", "Activation functions", "Forward & Backward propagation", "First neural network"], "hours": 6},
         {"title": "AI Applications & Tools", "topics": ["Computer Vision intro", "NLP intro", "Chatbot basics", "AI in industries"], "hours": 8},
         {"title": "AI Ethics & Future", "topics": ["Bias in AI", "Responsible AI", "AI governance", "Future of AI", "Career guidance"], "hours": 4},
         {"title": "Capstone Project", "topics": ["End-to-end AI project", "Problem definition", "Data collection", "Model building", "Presentation"], "hours": 4},
     ]},
    {"title": "Machine Learning with Python", "slug": "machine-learning-python",
     "category_slug": "ai-ml", "short_description": "Master ML algorithms, model building, evaluation, and deployment using Python.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 20000, "discount_price": 15999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["10+ ML algorithms", "Feature engineering", "Model evaluation & tuning", "Real-world projects", "Model deployment", "MLOps basics"],
     "tools_covered": ["Python", "scikit-learn", "Pandas", "NumPy", "Matplotlib", "Flask", "Jupyter"],
     "curriculum": [
         {"title": "Python for ML", "topics": ["NumPy", "Pandas", "Matplotlib/Seaborn", "Data manipulation"], "hours": 8},
         {"title": "Supervised Learning - Regression", "topics": ["Linear Regression", "Polynomial Regression", "Ridge & Lasso", "Gradient Descent"], "hours": 8},
         {"title": "Supervised Learning - Classification", "topics": ["Logistic Regression", "SVM", "Decision Trees", "Random Forest", "XGBoost"], "hours": 10},
         {"title": "Unsupervised Learning", "topics": ["K-Means", "Hierarchical Clustering", "DBSCAN", "PCA", "t-SNE"], "hours": 8},
         {"title": "Feature Engineering", "topics": ["Feature scaling", "Encoding", "Feature selection", "Imbalanced data"], "hours": 6},
         {"title": "Model Evaluation & Tuning", "topics": ["Cross-validation", "Grid/Random Search", "Confusion matrix", "ROC-AUC"], "hours": 6},
         {"title": "Ensemble Methods", "topics": ["Bagging", "Boosting", "Stacking", "Voting classifiers"], "hours": 6},
         {"title": "ML Project & Deployment", "topics": ["End-to-end project", "Flask API", "Model serialization", "Docker basics"], "hours": 8},
     ]},
    {"title": "Deep Learning & Neural Networks", "slug": "deep-learning-neural-networks",
     "category_slug": "ai-ml", "short_description": "Master deep learning with TensorFlow and PyTorch.",
     "level": "advanced", "duration_hours": 80, "duration_weeks": 10, "price": 25000, "discount_price": 19999,
     "is_featured": True,
     "highlights": ["TensorFlow & PyTorch", "CNN, RNN, LSTM, GAN", "Transfer Learning", "Transformers", "5+ projects"],
     "tools_covered": ["TensorFlow", "Keras", "PyTorch", "OpenCV", "Hugging Face"],
     "curriculum": [
         {"title": "Deep Learning Foundations", "topics": ["Perceptrons to DNNs", "Activation functions", "Loss functions", "Optimizers", "Regularization"], "hours": 10},
         {"title": "Convolutional Neural Networks", "topics": ["CNN architecture", "Filters & Feature maps", "Pooling", "VGG, ResNet", "Transfer Learning"], "hours": 12},
         {"title": "Recurrent Neural Networks", "topics": ["RNN basics", "LSTM & GRU", "Bidirectional RNNs", "Seq2Seq", "Attention"], "hours": 12},
         {"title": "Generative Models", "topics": ["Autoencoders", "VAE", "GANs", "Style Transfer", "Image Generation"], "hours": 10},
         {"title": "Transformers & Attention", "topics": ["Self-attention", "Multi-head attention", "Transformer architecture", "BERT", "GPT"], "hours": 12},
         {"title": "Advanced Topics", "topics": ["Object Detection", "Semantic Segmentation", "RL intro", "Model optimization"], "hours": 12},
         {"title": "Projects", "topics": ["Image classification", "Sentiment analysis", "Object detection", "Text generation", "Deployment"], "hours": 12},
     ]},
    {"title": "Natural Language Processing (NLP)", "slug": "natural-language-processing",
     "category_slug": "ai-ml", "short_description": "Complete NLP training — text preprocessing, transformers, BERT, GPT.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 18000, "discount_price": 14999,
     "is_featured": True,
     "highlights": ["Text preprocessing", "Word2Vec, GloVe", "BERT, GPT", "Sentiment analysis, NER", "Hugging Face"],
     "tools_covered": ["NLTK", "spaCy", "Hugging Face", "Gensim", "TensorFlow"],
     "curriculum": [
         {"title": "NLP Fundamentals", "topics": ["Tokenization", "Stemming & Lemmatization", "POS tagging", "NER"], "hours": 8},
         {"title": "Text Representation", "topics": ["Bag of Words", "TF-IDF", "Word2Vec", "GloVe", "FastText"], "hours": 8},
         {"title": "Classical NLP", "topics": ["Text classification", "Sentiment Analysis", "Topic Modeling", "Text Similarity"], "hours": 10},
         {"title": "Deep Learning for NLP", "topics": ["RNN/LSTM for text", "Sequence models", "Attention mechanism", "Seq2Seq"], "hours": 8},
         {"title": "Transformers & Modern NLP", "topics": ["BERT", "GPT family", "RoBERTa", "T5", "Fine-tuning"], "hours": 10},
         {"title": "NLP Projects", "topics": ["Chatbot", "Question Answering", "Summarization", "Machine Translation"], "hours": 6},
     ]},
    {"title": "Computer Vision with OpenCV", "slug": "computer-vision",
     "category_slug": "ai-ml", "short_description": "Image processing, object detection, face recognition, video analysis.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 18000, "discount_price": 14999,
     "highlights": ["OpenCV mastery", "Object detection (YOLO, SSD)", "Face recognition", "Image segmentation", "Real-time video"],
     "tools_covered": ["OpenCV", "TensorFlow", "PyTorch", "YOLO", "MediaPipe"],
     "curriculum": [
         {"title": "Image Processing Basics", "topics": ["Image manipulation", "Color spaces", "Filters", "Edge detection", "Histograms"], "hours": 8},
         {"title": "Feature Detection", "topics": ["Corner detection", "SIFT/SURF/ORB", "Feature matching", "Image stitching"], "hours": 8},
         {"title": "Object Detection", "topics": ["Haar Cascades", "HOG + SVM", "YOLO v5/v8", "SSD", "Faster R-CNN"], "hours": 12},
         {"title": "Face Analysis", "topics": ["Face detection", "Face recognition", "Emotion detection", "Face mesh"], "hours": 8},
         {"title": "Advanced CV", "topics": ["Semantic segmentation", "Instance segmentation", "Pose estimation", "OCR"], "hours": 8},
         {"title": "Projects", "topics": ["Real-time detection", "Face attendance", "Gesture recognition", "Document scanner"], "hours": 6},
     ]},
    {"title": "Generative AI & Large Language Models", "slug": "generative-ai-llm",
     "category_slug": "ai-ml", "short_description": "Master GPT, Claude, Gemini, Stable Diffusion, prompt engineering.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 25000, "discount_price": 19999,
     "is_featured": True, "is_trending": True, "is_bestseller": True,
     "highlights": ["GPT, Claude, Gemini, LLaMA", "Prompt engineering", "Building AI apps", "Stable Diffusion & DALL-E", "Ethics in Gen AI"],
     "tools_covered": ["OpenAI API", "Claude", "Gemini", "Hugging Face", "Stable Diffusion"],
     "curriculum": [
         {"title": "Gen AI Foundations", "topics": ["What is Generative AI?", "LLMs explained", "GPT architecture", "Tokenization"], "hours": 8},
         {"title": "Prompt Engineering", "topics": ["Zero-shot & Few-shot", "Chain-of-thought", "System prompts", "Prompt optimization"], "hours": 10},
         {"title": "LLM APIs & Integration", "topics": ["OpenAI API", "Claude API", "Gemini API", "Cost optimization", "Chatbots"], "hours": 10},
         {"title": "Image Generation", "topics": ["Stable Diffusion", "DALL-E", "Midjourney", "ControlNet", "Inpainting"], "hours": 8},
         {"title": "Building Gen AI Apps", "topics": ["AI writing assistant", "Code generation", "Content summarizer", "Multi-modal apps"], "hours": 12},
         {"title": "Ethics & Deployment", "topics": ["AI hallucinations", "Bias mitigation", "Content safety", "Production deployment"], "hours": 6},
         {"title": "Capstone Project", "topics": ["End-to-end Gen AI application"], "hours": 6},
     ]},
    {"title": "Prompt Engineering Masterclass", "slug": "prompt-engineering",
     "category_slug": "ai-ml", "short_description": "Expert prompt engineering for ChatGPT, Claude, Gemini.",
     "level": "beginner", "duration_hours": 30, "duration_weeks": 4, "price": 10000, "discount_price": 7999,
     "is_trending": True,
     "highlights": ["20+ prompting techniques", "Multi-modal prompting", "Enterprise prompt design", "Prompt testing"],
     "tools_covered": ["ChatGPT", "Claude", "Gemini", "Copilot", "Perplexity"],
     "curriculum": [
         {"title": "Prompt Basics", "topics": ["How LLMs work", "Token economy", "Temperature & parameters"], "hours": 4},
         {"title": "Core Techniques", "topics": ["Zero-shot", "Few-shot", "Chain-of-thought", "Role prompting"], "hours": 6},
         {"title": "Advanced Techniques", "topics": ["Tree-of-thought", "ReAct", "Self-consistency", "Meta-prompting"], "hours": 8},
         {"title": "Multi-Modal Prompting", "topics": ["Image prompts", "Document analysis", "Audio/Video prompting"], "hours": 6},
         {"title": "Enterprise Applications", "topics": ["Customer support bots", "Content generation", "Data analysis"], "hours": 6},
     ]},
    {"title": "LangChain & LLM Application Development", "slug": "langchain-llm-development",
     "category_slug": "ai-ml", "short_description": "Build production-grade LLM applications with LangChain.",
     "level": "advanced", "duration_hours": 60, "duration_weeks": 8, "price": 25000, "discount_price": 19999,
     "is_featured": True, "is_trending": True,
     "highlights": ["LangChain mastery", "RAG pipelines", "Vector databases", "Memory & chains", "Production deployment"],
     "tools_covered": ["LangChain", "LlamaIndex", "Pinecone", "ChromaDB", "Weaviate", "FAISS"],
     "curriculum": [
         {"title": "LangChain Fundamentals", "topics": ["Architecture", "Models, Prompts, Chains", "Output parsers", "Memory", "LCEL"], "hours": 10},
         {"title": "RAG", "topics": ["What is RAG?", "Document loaders", "Text splitters", "Embeddings", "Vector stores"], "hours": 12},
         {"title": "Vector Databases", "topics": ["Pinecone", "ChromaDB", "Weaviate", "FAISS", "Similarity search"], "hours": 8},
         {"title": "Advanced Chains & Agents", "topics": ["Sequential chains", "Router chains", "Agents & Tools", "Custom tools"], "hours": 10},
         {"title": "LlamaIndex", "topics": ["Overview", "Data connectors", "Index types", "Query engines"], "hours": 8},
         {"title": "Production Deployment", "topics": ["LangServe", "FastAPI", "Monitoring", "Scaling"], "hours": 6},
         {"title": "Projects", "topics": ["Document Q&A", "Multi-document RAG", "AI research assistant"], "hours": 6},
     ]},
    {"title": "Agentic AI & Autonomous Agents", "slug": "agentic-ai-autonomous-agents",
     "category_slug": "ai-ml", "short_description": "Build autonomous AI agents with multi-agent systems.",
     "level": "advanced", "duration_hours": 60, "duration_weeks": 8, "price": 30000, "discount_price": 24999,
     "is_featured": True, "is_trending": True, "is_bestseller": True,
     "highlights": ["Agentic AI patterns", "CrewAI, AutoGen, LangGraph", "Tool-use & Function calling", "Multi-agent orchestration"],
     "tools_covered": ["LangGraph", "CrewAI", "AutoGen", "OpenAI Function Calling", "Anthropic Tool Use"],
     "curriculum": [
         {"title": "Agentic AI Foundations", "topics": ["What are AI Agents?", "Agent vs Chatbot", "ReAct pattern", "Planning"], "hours": 8},
         {"title": "Tool Use & Function Calling", "topics": ["OpenAI Function Calling", "Anthropic Tool Use", "Custom tools", "API integration"], "hours": 10},
         {"title": "LangGraph", "topics": ["Architecture", "State machines", "Conditional routing", "Human-in-the-loop"], "hours": 12},
         {"title": "CrewAI", "topics": ["CrewAI framework", "Agents & tasks", "Sequential & hierarchical crews", "Custom tools"], "hours": 10},
         {"title": "AutoGen & Multi-Agent", "topics": ["AutoGen framework", "Multi-agent conversations", "Group chat", "Code execution"], "hours": 10},
         {"title": "Production Agents", "topics": ["Error handling", "Memory", "Cost optimization", "Monitoring", "Capstone project"], "hours": 10},
     ]},
    {"title": "MCP (Model Context Protocol)", "slug": "mcp-model-context-protocol",
     "category_slug": "ai-ml", "short_description": "Master Anthropic's MCP — connect AI to data sources and tools.",
     "level": "advanced", "duration_hours": 40, "duration_weeks": 5, "price": 22000, "discount_price": 17999,
     "is_trending": True,
     "highlights": ["MCP architecture", "Building MCP servers", "Client integration", "Enterprise connectors", "Security"],
     "tools_covered": ["MCP SDK", "Python", "TypeScript", "Claude Desktop", "Cursor IDE"],
     "curriculum": [
         {"title": "MCP Fundamentals", "topics": ["What is MCP?", "Architecture", "Servers, Clients, Hosts", "Resources, Tools, Prompts"], "hours": 8},
         {"title": "Building MCP Servers", "topics": ["Python SDK", "TypeScript SDK", "Resource handlers", "Tool handlers"], "hours": 10},
         {"title": "MCP Client Integration", "topics": ["Claude Desktop", "Cursor IDE", "Custom clients", "Multi-server"], "hours": 8},
         {"title": "Enterprise MCP", "topics": ["Database connectors", "API integration", "Auth & security", "Rate limiting"], "hours": 8},
         {"title": "Production MCP", "topics": ["Error handling", "Logging", "Scaling", "Project"], "hours": 6},
     ]},
    {"title": "Data Science with Python", "slug": "data-science-python",
     "category_slug": "ai-ml", "short_description": "Complete data science bootcamp — EDA, statistics, ML.",
     "level": "beginner", "duration_hours": 80, "duration_weeks": 12, "price": 22000, "discount_price": 17999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["Python from scratch", "Statistics & Probability", "EDA with Pandas", "ML models", "Business projects"],
     "tools_covered": ["Python", "Pandas", "NumPy", "Matplotlib", "Seaborn", "scikit-learn", "SQL", "Tableau"],
     "curriculum": [
         {"title": "Python Programming", "topics": ["Variables", "Control flow", "Functions", "OOP", "File handling"], "hours": 12},
         {"title": "Statistics & Probability", "topics": ["Descriptive stats", "Distributions", "Hypothesis testing", "Correlation"], "hours": 10},
         {"title": "Data Analysis with Pandas", "topics": ["DataFrames", "Data cleaning", "Groupby", "Merging", "Time series"], "hours": 10},
         {"title": "Data Visualization", "topics": ["Matplotlib", "Seaborn", "Plotly", "Dashboard basics"], "hours": 8},
         {"title": "SQL for Data Science", "topics": ["SQL fundamentals", "Joins", "Subqueries", "Window functions"], "hours": 8},
         {"title": "Machine Learning", "topics": ["Supervised learning", "Unsupervised learning", "Model evaluation"], "hours": 16},
         {"title": "Projects", "topics": ["Customer segmentation", "Churn prediction", "Sales forecasting", "Portfolio"], "hours": 16},
     ]},
    {"title": "MLOps & ML Engineering", "slug": "mlops-ml-engineering",
     "category_slug": "ai-ml", "short_description": "End-to-end MLOps — ML pipelines, experiment tracking, model serving.",
     "level": "advanced", "duration_hours": 50, "duration_weeks": 7, "price": 22000, "discount_price": 17999,
     "highlights": ["ML pipeline automation", "MLflow tracking", "Model serving", "CI/CD for ML", "Model monitoring"],
     "tools_covered": ["MLflow", "DVC", "BentoML", "Airflow", "Docker", "Kubernetes"],
     "curriculum": [
         {"title": "MLOps Foundations", "topics": ["What is MLOps?", "ML lifecycle", "DevOps vs MLOps"], "hours": 6},
         {"title": "Experiment Tracking", "topics": ["MLflow", "Experiment logging", "Model registry", "DVC"], "hours": 8},
         {"title": "ML Pipelines", "topics": ["Airflow/Prefect", "Pipeline orchestration", "Feature stores"], "hours": 10},
         {"title": "Model Serving", "topics": ["BentoML", "TF Serving", "FastAPI serving", "Batch vs Real-time"], "hours": 8},
         {"title": "CI/CD for ML", "topics": ["GitHub Actions for ML", "Automated testing", "Blue-green deployment"], "hours": 8},
         {"title": "Monitoring", "topics": ["Data drift", "Performance monitoring", "Alerting", "Retraining"], "hours": 6},
         {"title": "Project", "topics": ["End-to-end MLOps pipeline"], "hours": 4},
     ]},
    # SAP
    {"title": "SAP ERP Fundamentals", "slug": "sap-erp-fundamentals",
     "category_slug": "sap", "short_description": "Complete introduction to SAP ERP system.",
     "level": "beginner", "duration_hours": 40, "duration_weeks": 6, "price": 18000, "discount_price": 14999,
     "is_featured": True,
     "highlights": ["SAP system landscape", "Core modules overview", "Business process integration", "SAP GUI navigation"],
     "tools_covered": ["SAP GUI", "SAP S/4HANA", "SAP Fiori"],
     "curriculum": [
         {"title": "Introduction to SAP", "topics": ["What is ERP?", "SAP overview", "SAP modules", "Career in SAP"], "hours": 6},
         {"title": "SAP Navigation", "topics": ["SAP GUI", "Transaction codes", "Menu navigation", "SAP Fiori intro"], "hours": 8},
         {"title": "SAP MM", "topics": ["Procurement", "Purchase orders", "Inventory management", "Vendor master"], "hours": 8},
         {"title": "SAP SD", "topics": ["Sales process", "Order to cash", "Pricing", "Delivery & billing"], "hours": 8},
         {"title": "SAP FICO", "topics": ["GL accounting", "AP/AR", "Cost center accounting", "Financial reports"], "hours": 8},
         {"title": "Integration", "topics": ["Cross-module integration", "S/4HANA migration", "SAP BTP overview"], "hours": 2},
     ]},
    {"title": "SAP S/4HANA", "slug": "sap-s4hana",
     "category_slug": "sap", "short_description": "Master SAP S/4HANA — architecture, migration, Fiori apps.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 25000, "discount_price": 19999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["S/4HANA architecture", "HANA in-memory", "Fiori UX", "Migration strategies", "Simplified data model"],
     "tools_covered": ["SAP S/4HANA", "SAP HANA Studio", "SAP Fiori", "SAP BTP"],
     "curriculum": [
         {"title": "S/4HANA Overview", "topics": ["Architecture", "vs ECC", "Simplified data model", "HANA database"], "hours": 10},
         {"title": "S/4HANA Finance", "topics": ["Universal Journal", "Central Finance", "Asset Accounting", "Cash Management"], "hours": 12},
         {"title": "S/4HANA Logistics", "topics": ["MRP Live", "Extended Warehouse", "Embedded Analytics"], "hours": 12},
         {"title": "SAP Fiori", "topics": ["Fiori launchpad", "Fiori apps", "UX guidelines", "Fiori Elements"], "hours": 10},
         {"title": "Migration", "topics": ["Brownfield vs Greenfield", "System conversion", "Data migration", "Testing"], "hours": 10},
         {"title": "Project", "topics": ["End-to-end S/4HANA scenario", "Configuration", "Go-live preparation"], "hours": 6},
     ]},
    {"title": "SAP Commerce Cloud (Hybris)", "slug": "sap-commerce-cloud",
     "category_slug": "sap", "short_description": "Master SAP Commerce Cloud — architecture, storefront, OCC API, Spartacus.",
     "level": "advanced", "duration_hours": 80, "duration_weeks": 10, "price": 35000, "discount_price": 29999,
     "is_featured": True, "is_trending": True,
     "highlights": ["Commerce Cloud architecture", "Data modeling & Impex", "Storefront customization", "OCC REST APIs", "Spartacus framework"],
     "tools_covered": ["SAP Commerce Cloud", "Spartacus", "Angular", "Java", "Spring", "Solr"],
     "curriculum": [
         {"title": "Commerce Cloud Fundamentals", "topics": ["Architecture", "Type system", "Data modeling", "Impex"], "hours": 12},
         {"title": "Service Layer & Extensions", "topics": ["Service layer", "Extension creation", "Interceptors", "Cronjobs"], "hours": 12},
         {"title": "Storefront & Accelerator", "topics": ["Accelerator architecture", "CMS components", "Checkout flow", "B2B"], "hours": 12},
         {"title": "OCC APIs", "topics": ["REST API architecture", "Custom endpoints", "Authentication", "Swagger"], "hours": 10},
         {"title": "Spartacus", "topics": ["Architecture", "Angular basics", "Component override", "Lazy loading", "SSR"], "hours": 16},
         {"title": "Cloud & DevOps", "topics": ["Cloud deployment", "CI/CD", "Monitoring", "Performance tuning"], "hours": 10},
         {"title": "Project", "topics": ["End-to-end e-commerce project"], "hours": 8},
     ]},
    {"title": "SAP CPI (Cloud Platform Integration)", "slug": "sap-cpi-integration",
     "category_slug": "sap", "short_description": "Master SAP CPI — integration flows, adapters, mappings.",
     "level": "advanced", "duration_hours": 60, "duration_weeks": 8, "price": 28000, "discount_price": 22999,
     "is_featured": True, "is_trending": True,
     "highlights": ["Integration flow design", "Message mapping & Groovy", "Adapters (SOAP, REST, SFTP)", "Error handling", "BTP Integration Suite"],
     "tools_covered": ["SAP CPI", "SAP BTP", "Groovy", "XSLT", "Postman"],
     "curriculum": [
         {"title": "CPI Fundamentals", "topics": ["Integration Suite", "CPI architecture", "Tenant setup"], "hours": 8},
         {"title": "Integration Flows", "topics": ["iFlow design", "Content modifier", "Router", "Splitter", "Aggregator"], "hours": 12},
         {"title": "Adapters", "topics": ["SOAP", "REST/HTTP", "SFTP", "IDoc", "OData", "Mail"], "hours": 10},
         {"title": "Message Processing", "topics": ["Message mapping", "XSLT", "Groovy scripts", "Value mapping"], "hours": 10},
         {"title": "Error Handling & Security", "topics": ["Exception handling", "Retry", "Monitoring", "OAuth/Certificate"], "hours": 10},
         {"title": "Advanced", "topics": ["API management", "Open connectors", "B2B integration", "Project"], "hours": 10},
     ]},
    {"title": "SAP FICO", "slug": "sap-fico",
     "category_slug": "sap", "short_description": "Comprehensive SAP FICO — GL, AP, AR, Asset, Cost Center, Profit Center.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 22000, "discount_price": 17999,
     "is_bestseller": True,
     "highlights": ["Complete FI & CO config", "Real-time scenarios", "S/4HANA Finance", "Month-end closing", "Certification prep"],
     "tools_covered": ["SAP S/4HANA", "SAP GUI", "SAP Fiori"],
     "curriculum": [
         {"title": "FI - General Ledger", "topics": ["Company code", "Chart of accounts", "GL master data", "Document posting"], "hours": 10},
         {"title": "FI - AP/AR", "topics": ["Vendor master", "Invoice posting", "Payment processing", "Customer master", "Dunning"], "hours": 10},
         {"title": "FI - Asset Accounting", "topics": ["Asset classes", "Asset master", "Depreciation", "Asset transactions"], "hours": 8},
         {"title": "CO - Cost Center Accounting", "topics": ["Cost elements", "Cost centers", "Activity types", "Assessment"], "hours": 10},
         {"title": "CO - Profit Center", "topics": ["Profit centers", "Profitability analysis", "Internal orders"], "hours": 8},
         {"title": "Integration & Reporting", "topics": ["FI-CO integration", "FI-MM/SD integration", "Financial reports", "Month-end closing"], "hours": 8},
         {"title": "S/4HANA Finance", "topics": ["Universal Journal", "Central Finance", "Fiori apps for Finance"], "hours": 6},
     ]},
    {"title": "SAP ABAP Programming", "slug": "sap-abap-programming",
     "category_slug": "sap", "short_description": "Learn SAP ABAP — reports, data dictionary, ALV, BAPIs, ABAP on HANA.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 22000, "discount_price": 17999,
     "highlights": ["ABAP from scratch", "Data dictionary", "ALV reports", "BAPIs & RFC", "Enhancement framework", "ABAP on HANA"],
     "tools_covered": ["ABAP Workbench", "Eclipse ADT", "SAP HANA Studio"],
     "curriculum": [
         {"title": "ABAP Basics", "topics": ["Syntax", "Data types", "Control structures", "Internal tables"], "hours": 10},
         {"title": "Data Dictionary", "topics": ["Tables", "Views", "Data elements", "Domains", "Search helps"], "hours": 8},
         {"title": "Reports & ALV", "topics": ["Classical reports", "Interactive reports", "ALV Grid", "Selection screens"], "hours": 10},
         {"title": "Modularization", "topics": ["Function modules", "Classes & Methods", "BAPIs", "RFC"], "hours": 8},
         {"title": "Enhancements", "topics": ["User exits", "BAdIs", "Enhancement spots", "Implicit enhancements"], "hours": 8},
         {"title": "ABAP on HANA", "topics": ["ABAP for HANA", "CDS Views", "AMDP", "Code pushdown", "Eclipse ADT"], "hours": 10},
         {"title": "Project", "topics": ["Custom ABAP application"], "hours": 6},
     ]},
    {"title": "SAP UI5 & Fiori Development", "slug": "sap-ui5-fiori",
     "category_slug": "sap", "short_description": "Build SAP Fiori apps with SAPUI5.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 22000, "discount_price": 17999,
     "highlights": ["SAPUI5 framework", "MVC architecture", "OData v2/v4", "Fiori Elements", "SAP BAS"],
     "tools_covered": ["SAPUI5", "SAP BAS", "SAP Fiori Launchpad", "OData"],
     "curriculum": [
         {"title": "UI5 Fundamentals", "topics": ["Architecture", "MVC", "Controls", "Data binding", "Routing"], "hours": 10},
         {"title": "UI5 Advanced", "topics": ["Fragments", "Custom controls", "Formatters", "i18n", "Responsive"], "hours": 10},
         {"title": "OData Services", "topics": ["OData v2/v4", "CRUD", "Filters", "Navigation", "Batch"], "hours": 10},
         {"title": "Fiori Elements", "topics": ["List Report", "Object Page", "Worklist", "Analytical List"], "hours": 8},
         {"title": "Deployment", "topics": ["SAP BAS setup", "Testing", "Deployment to BTP", "Fiori Launchpad"], "hours": 6},
         {"title": "Project", "topics": ["Custom Fiori application"], "hours": 6},
     ]},
    # Programming
    {"title": "Python Full Stack Development", "slug": "python-full-stack",
     "category_slug": "programming", "short_description": "Complete Python full-stack — Django, React, PostgreSQL.",
     "level": "beginner", "duration_hours": 80, "duration_weeks": 12, "price": 22000, "discount_price": 17999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["Python from scratch", "Django & DRF", "React frontend", "PostgreSQL", "Docker & deployment"],
     "tools_covered": ["Python", "Django", "DRF", "React", "PostgreSQL", "Docker", "Git"],
     "curriculum": [
         {"title": "Python Core", "topics": ["Variables", "Control flow", "Functions", "OOP", "Modules"], "hours": 12},
         {"title": "Django Backend", "topics": ["Models & ORM", "Views & URLs", "Templates", "Authentication", "Admin"], "hours": 16},
         {"title": "Django REST Framework", "topics": ["Serializers", "ViewSets", "JWT", "Permissions", "Pagination"], "hours": 12},
         {"title": "React Frontend", "topics": ["JSX", "Hooks", "State management", "React Router", "API integration"], "hours": 16},
         {"title": "Database & DevOps", "topics": ["PostgreSQL", "Docker", "Nginx", "CI/CD", "Cloud deployment"], "hours": 12},
         {"title": "Projects", "topics": ["E-commerce", "Blog CMS", "Task management", "Social media", "Portfolio"], "hours": 12},
     ]},
    {"title": "Java Full Stack Development", "slug": "java-full-stack",
     "category_slug": "programming", "short_description": "Core Java, Spring Boot, Microservices, Angular/React.",
     "level": "beginner", "duration_hours": 100, "duration_weeks": 14, "price": 25000, "discount_price": 19999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["Core Java to Advanced", "Spring Boot & Microservices", "Angular or React", "MySQL/PostgreSQL", "Docker & Kubernetes"],
     "tools_covered": ["Java", "Spring Boot", "Hibernate", "Angular", "MySQL", "Docker", "AWS"],
     "curriculum": [
         {"title": "Core Java", "topics": ["OOP", "Collections", "Generics", "Streams", "Multithreading"], "hours": 16},
         {"title": "Advanced Java", "topics": ["JDBC", "Servlets", "JSP", "Design patterns", "JUnit"], "hours": 12},
         {"title": "Spring Framework", "topics": ["Spring Core", "Spring Boot", "Spring MVC", "Spring Data JPA", "Spring Security"], "hours": 16},
         {"title": "Microservices", "topics": ["Architecture", "Spring Cloud", "API Gateway", "Service discovery", "Circuit breaker"], "hours": 12},
         {"title": "Frontend", "topics": ["TypeScript", "Components", "Services", "Routing", "State management"], "hours": 16},
         {"title": "Database & DevOps", "topics": ["MySQL/PostgreSQL", "Hibernate", "Docker", "Kubernetes", "CI/CD"], "hours": 12},
         {"title": "Projects", "topics": ["E-commerce microservices", "Banking app", "Hotel booking", "Portfolio"], "hours": 16},
     ]},
    {"title": "MERN Stack Development", "slug": "mern-stack",
     "category_slug": "programming", "short_description": "Complete MERN Stack — MongoDB, Express, React, Node.js.",
     "level": "beginner", "duration_hours": 80, "duration_weeks": 10, "price": 20000, "discount_price": 15999,
     "is_featured": True, "is_trending": True,
     "highlights": ["MongoDB, Express, React, Node", "REST API", "JWT Authentication", "Redux", "6+ projects"],
     "tools_covered": ["MongoDB", "Express.js", "React", "Node.js", "Redux", "JWT", "Socket.io"],
     "curriculum": [
         {"title": "JavaScript Advanced", "topics": ["ES6+", "Promises", "Async/Await", "Closures", "Modules"], "hours": 10},
         {"title": "Node.js & Express", "topics": ["Node.js runtime", "Express setup", "Routing", "Middleware"], "hours": 14},
         {"title": "MongoDB", "topics": ["NoSQL concepts", "CRUD", "Mongoose ODM", "Aggregation", "Indexing"], "hours": 10},
         {"title": "React", "topics": ["JSX", "Hooks", "Context API", "Redux Toolkit", "React Router"], "hours": 16},
         {"title": "Full Stack Integration", "topics": ["JWT auth", "REST API integration", "File uploads", "Socket.io", "Deployment"], "hours": 14},
         {"title": "Projects", "topics": ["Social media", "E-commerce", "Chat app", "Job portal", "Portfolio"], "hours": 16},
     ]},
    {"title": "React.js Development", "slug": "react-development",
     "category_slug": "programming", "short_description": "Master React.js — Hooks, Redux, Next.js, testing.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 18000, "discount_price": 14999,
     "is_featured": True,
     "highlights": ["React 18+", "Hooks deep dive", "Redux Toolkit & Zustand", "Next.js SSR/SSG", "Testing"],
     "tools_covered": ["React", "Next.js", "Redux Toolkit", "Zustand", "Tailwind CSS", "Jest"],
     "curriculum": [
         {"title": "React Fundamentals", "topics": ["JSX", "Components", "Props", "State", "Events", "Lists"], "hours": 10},
         {"title": "React Hooks", "topics": ["useState", "useEffect", "useContext", "useReducer", "Custom hooks"], "hours": 10},
         {"title": "State Management", "topics": ["Context API", "Redux Toolkit", "Zustand", "React Query"], "hours": 10},
         {"title": "Routing & Forms", "topics": ["React Router 6", "React Hook Form", "Zod validation"], "hours": 8},
         {"title": "Next.js", "topics": ["SSR & SSG", "App Router", "Server Components", "API Routes"], "hours": 12},
         {"title": "Projects", "topics": ["Dashboard", "E-commerce", "Blog with Next.js", "Portfolio"], "hours": 10},
     ]},
    {"title": "Angular Development", "slug": "angular-development",
     "category_slug": "programming", "short_description": "Master Angular — TypeScript, RxJS, NgRx, enterprise apps.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 18000, "discount_price": 14999,
     "highlights": ["Angular 17+", "TypeScript mastery", "RxJS Observables", "NgRx state management", "Enterprise patterns"],
     "tools_covered": ["Angular", "TypeScript", "RxJS", "NgRx", "Angular Material"],
     "curriculum": [
         {"title": "TypeScript & Angular Basics", "topics": ["TypeScript", "Angular CLI", "Components", "Data binding"], "hours": 10},
         {"title": "Angular Core", "topics": ["Directives", "Pipes", "Services & DI", "HTTP Client", "Routing"], "hours": 12},
         {"title": "RxJS & Reactive", "topics": ["Observables", "Operators", "Subjects", "Reactive forms"], "hours": 10},
         {"title": "State Management", "topics": ["NgRx Store", "Actions", "Reducers", "Effects", "Selectors"], "hours": 10},
         {"title": "Advanced Angular", "topics": ["Lazy loading", "Standalone components", "Signals", "Testing"], "hours": 10},
         {"title": "Projects", "topics": ["Admin dashboard", "E-commerce frontend", "Real-time app"], "hours": 8},
     ]},
    {"title": "PHP & Laravel Development", "slug": "php-laravel",
     "category_slug": "programming", "short_description": "Master PHP with Laravel — MVC, Eloquent, REST APIs.",
     "level": "beginner", "duration_hours": 60, "duration_weeks": 8, "price": 15000, "discount_price": 11999,
     "highlights": ["PHP from basics", "Laravel framework", "Eloquent ORM", "REST API", "Vue.js frontend"],
     "tools_covered": ["PHP", "Laravel", "MySQL", "Vue.js", "Composer", "Git"],
     "curriculum": [
         {"title": "PHP Fundamentals", "topics": ["Syntax", "Arrays & functions", "OOP", "File handling", "MySQL"], "hours": 12},
         {"title": "Laravel Framework", "topics": ["MVC", "Routing", "Controllers", "Blade templates", "Eloquent ORM"], "hours": 16},
         {"title": "Laravel Advanced", "topics": ["Authentication", "Authorization", "Events & Queues", "REST API", "Testing"], "hours": 12},
         {"title": "Frontend Integration", "topics": ["Vue.js basics", "Laravel + Vue.js", "Inertia.js", "Tailwind CSS"], "hours": 12},
         {"title": "Projects", "topics": ["Blog CMS", "E-commerce", "REST API project", "SaaS application"], "hours": 8},
     ]},
    {"title": ".NET Full Stack Development", "slug": "dotnet-full-stack",
     "category_slug": "programming", "short_description": "Master .NET — C#, ASP.NET Core, Entity Framework, Azure.",
     "level": "beginner", "duration_hours": 80, "duration_weeks": 10, "price": 22000, "discount_price": 17999,
     "is_featured": True,
     "highlights": ["C# programming", "ASP.NET Core MVC & Web API", "Entity Framework", "Blazor", "Azure deployment"],
     "tools_covered": ["C#", "ASP.NET Core", "Entity Framework", "Angular/Blazor", "SQL Server", "Azure"],
     "curriculum": [
         {"title": "C# Programming", "topics": ["Syntax & OOP", "Collections", "LINQ", "Async/Await", "Generics"], "hours": 14},
         {"title": "ASP.NET Core", "topics": ["MVC", "Razor Pages", "Routing", "Middleware", "DI"], "hours": 14},
         {"title": "Web API & EF Core", "topics": ["REST API", "Entity Framework Core", "JWT auth", "Repository pattern"], "hours": 14},
         {"title": "Frontend", "topics": ["Blazor WebAssembly", "Angular integration", "SignalR", "Identity UI"], "hours": 14},
         {"title": "Azure & DevOps", "topics": ["Azure App Service", "Azure SQL", "Azure DevOps", "Docker"], "hours": 12},
         {"title": "Projects", "topics": ["Enterprise CRM", "E-commerce API", "Real-time chat", "Portfolio"], "hours": 12},
     ]},
    {"title": "Node.js Backend Development", "slug": "nodejs-backend",
     "category_slug": "programming", "short_description": "Master Node.js — Express, Nest.js, GraphQL, microservices.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 18000, "discount_price": 14999,
     "highlights": ["Node.js runtime", "Express & Nest.js", "REST & GraphQL", "MongoDB & PostgreSQL", "Microservices"],
     "tools_covered": ["Node.js", "Express", "Nest.js", "MongoDB", "PostgreSQL", "GraphQL", "Redis"],
     "curriculum": [
         {"title": "Node.js Core", "topics": ["Event loop", "Modules", "File system", "Streams", "Cluster"], "hours": 10},
         {"title": "Express Framework", "topics": ["Routing", "Middleware", "Error handling", "File uploads", "Security"], "hours": 10},
         {"title": "Databases", "topics": ["MongoDB + Mongoose", "PostgreSQL + Prisma", "Redis caching"], "hours": 10},
         {"title": "Authentication & Security", "topics": ["JWT", "OAuth 2.0", "Passport.js", "Rate limiting", "Helmet"], "hours": 8},
         {"title": "Nest.js", "topics": ["Architecture", "Modules", "Controllers", "Providers", "Guards"], "hours": 10},
         {"title": "Advanced", "topics": ["GraphQL", "WebSockets", "Microservices", "Docker", "Testing"], "hours": 12},
     ]},
    {"title": "Golang (Go) Development", "slug": "golang-development",
     "category_slug": "programming", "short_description": "Learn Go — concurrency, microservices, gRPC.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 18000, "discount_price": 14999,
     "highlights": ["Go from scratch", "Goroutines & Channels", "REST & gRPC APIs", "Microservices", "Docker & Kubernetes"],
     "tools_covered": ["Go", "Gin/Echo", "gRPC", "PostgreSQL", "Docker", "Kubernetes"],
     "curriculum": [
         {"title": "Go Fundamentals", "topics": ["Syntax", "Data types", "Functions", "Structs", "Interfaces"], "hours": 10},
         {"title": "Concurrency", "topics": ["Goroutines", "Channels", "Select", "Mutex", "WaitGroups"], "hours": 10},
         {"title": "Web Development", "topics": ["Gin/Echo", "REST APIs", "Middleware", "GORM", "Authentication"], "hours": 12},
         {"title": "Advanced Go", "topics": ["gRPC", "Protocol Buffers", "Microservices", "Message queues", "Testing"], "hours": 12},
         {"title": "DevOps", "topics": ["Docker", "Kubernetes", "CI/CD", "Monitoring", "Project"], "hours": 6},
     ]},
    # Cloud
    {"title": "AWS Solutions Architect", "slug": "aws-solutions-architect",
     "category_slug": "cloud", "short_description": "AWS SAA-C03 certification prep.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 20000, "discount_price": 15999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["AWS SAA-C03 exam prep", "Hands-on labs", "Architecture patterns", "Cost optimization", "Security"],
     "tools_covered": ["AWS Console", "AWS CLI", "CloudFormation", "Terraform"],
     "curriculum": [
         {"title": "AWS Fundamentals", "topics": ["Cloud concepts", "AWS infrastructure", "IAM", "Billing"], "hours": 8},
         {"title": "Compute", "topics": ["EC2", "Lambda", "ECS/EKS", "Auto Scaling", "Load Balancers"], "hours": 10},
         {"title": "Storage & Databases", "topics": ["S3", "EBS", "RDS", "DynamoDB", "ElastiCache", "Aurora"], "hours": 10},
         {"title": "Networking", "topics": ["VPC", "Subnets", "NAT Gateway", "Route 53", "CloudFront"], "hours": 10},
         {"title": "Security & Monitoring", "topics": ["KMS", "WAF", "CloudWatch", "CloudTrail", "GuardDuty"], "hours": 8},
         {"title": "Architecture & Exam", "topics": ["Well-Architected Framework", "Practice exams", "Tips"], "hours": 8},
         {"title": "Hands-on Labs", "topics": ["3-tier web app", "Serverless", "Data lake", "DR setup"], "hours": 6},
     ]},
    {"title": "Docker & Kubernetes", "slug": "docker-kubernetes",
     "category_slug": "cloud", "short_description": "Master containerization and orchestration.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 18000, "discount_price": 14999,
     "is_featured": True, "is_trending": True,
     "highlights": ["Docker from scratch", "Kubernetes architecture", "Helm charts", "Service mesh", "Production deployment"],
     "tools_covered": ["Docker", "Kubernetes", "Helm", "Istio", "Prometheus", "Grafana"],
     "curriculum": [
         {"title": "Docker Fundamentals", "topics": ["Containers vs VMs", "Dockerfile", "Docker Compose", "Networking", "Volumes"], "hours": 12},
         {"title": "Kubernetes Core", "topics": ["K8s architecture", "Pods", "Deployments", "Services", "ConfigMaps"], "hours": 12},
         {"title": "K8s Advanced", "topics": ["StatefulSets", "DaemonSets", "Ingress", "Persistent Volumes", "RBAC"], "hours": 10},
         {"title": "Helm & Service Mesh", "topics": ["Helm charts", "Istio", "Traffic management", "Observability"], "hours": 8},
         {"title": "Production", "topics": ["Monitoring", "Logging", "Auto-scaling", "CI/CD", "Security"], "hours": 8},
     ]},
    {"title": "DevOps Engineering", "slug": "devops-engineering",
     "category_slug": "cloud", "short_description": "Complete DevOps — CI/CD, Terraform, Ansible, monitoring.",
     "level": "intermediate", "duration_hours": 70, "duration_weeks": 10, "price": 22000, "discount_price": 17999,
     "is_featured": True, "is_bestseller": True,
     "highlights": ["CI/CD pipelines", "Infrastructure as Code", "Jenkins/GitHub Actions", "Monitoring", "SRE practices"],
     "tools_covered": ["Jenkins", "Terraform", "Ansible", "GitHub Actions", "Prometheus", "Grafana", "Docker", "Kubernetes"],
     "curriculum": [
         {"title": "DevOps Foundations", "topics": ["DevOps culture", "Agile", "Git", "Branching strategies"], "hours": 8},
         {"title": "CI/CD", "topics": ["Jenkins", "GitHub Actions", "GitLab CI", "ArgoCD", "Blue-green deployment"], "hours": 12},
         {"title": "Infrastructure as Code", "topics": ["Terraform", "HCL", "Modules", "Ansible playbooks"], "hours": 14},
         {"title": "Containerization", "topics": ["Docker", "Kubernetes", "Helm", "Container security"], "hours": 12},
         {"title": "Monitoring", "topics": ["Prometheus", "Grafana", "ELK Stack", "Distributed tracing", "Alerting"], "hours": 10},
         {"title": "Cloud & Security", "topics": ["AWS/Azure DevOps", "Security scanning", "Secrets management"], "hours": 8},
         {"title": "SRE Practices", "topics": ["SRE principles", "Error budgets", "Incident management", "Chaos engineering"], "hours": 6},
     ]},
    {"title": "Terraform & Infrastructure as Code", "slug": "terraform-iac",
     "category_slug": "cloud", "short_description": "Master Terraform — HCL, modules, multi-cloud provisioning.",
     "level": "intermediate", "duration_hours": 40, "duration_weeks": 5, "price": 15000, "discount_price": 11999,
     "highlights": ["Terraform from scratch", "HCL language", "Module development", "State management", "Multi-cloud"],
     "tools_covered": ["Terraform", "AWS", "Azure", "Terraform Cloud", "Terragrunt"],
     "curriculum": [
         {"title": "Terraform Basics", "topics": ["IaC concepts", "HCL syntax", "Resources", "Variables", "Outputs"], "hours": 8},
         {"title": "State & Workspace", "topics": ["State management", "Remote backends", "Workspaces", "Import"], "hours": 8},
         {"title": "Modules & Reusability", "topics": ["Module creation", "Module registry", "Composition", "Versioning"], "hours": 8},
         {"title": "Advanced", "topics": ["Provisioners", "Dynamic blocks", "for_each", "Lifecycle rules"], "hours": 8},
         {"title": "Production", "topics": ["CI/CD integration", "Terraform Cloud", "Terragrunt", "Security"], "hours": 8},
     ]},
    {"title": "Azure Fundamentals (AZ-900)", "slug": "azure-fundamentals-az900",
     "category_slug": "cloud", "short_description": "Azure AZ-900 certification prep.",
     "level": "beginner", "duration_hours": 30, "duration_weeks": 4, "price": 12000, "discount_price": 8999,
     "is_featured": True,
     "highlights": ["AZ-900 exam prep", "Cloud concepts", "Azure core services", "Security & compliance"],
     "tools_covered": ["Azure Portal", "Azure CLI", "Azure PowerShell"],
     "curriculum": [
         {"title": "Cloud Concepts", "topics": ["Cloud models", "IaaS/PaaS/SaaS", "Public/Private/Hybrid"], "hours": 6},
         {"title": "Azure Core Services", "topics": ["VMs", "App Service", "Functions", "Storage", "Databases", "Networking"], "hours": 10},
         {"title": "Security & Compliance", "topics": ["Azure AD", "MFA", "RBAC", "Network Security", "Key Vault"], "hours": 6},
         {"title": "Pricing & Governance", "topics": ["Pricing calculator", "Cost management", "Azure Policy", "SLAs"], "hours": 4},
         {"title": "Exam Prep", "topics": ["Practice tests", "Question patterns", "Tips", "Mock exam"], "hours": 4},
     ]},
    # Cybersecurity
    {"title": "Ethical Hacking & Penetration Testing", "slug": "ethical-hacking",
     "category_slug": "cybersecurity", "short_description": "Learn ethical hacking — network & web app pentesting.",
     "level": "intermediate", "duration_hours": 60, "duration_weeks": 8, "price": 22000, "discount_price": 17999,
     "is_featured": True,
     "highlights": ["CEH-aligned curriculum", "Network & web pentesting", "Vulnerability assessment", "Kali Linux", "Hands-on labs"],
     "tools_covered": ["Kali Linux", "Metasploit", "Burp Suite", "Nmap", "Wireshark", "OWASP ZAP"],
     "curriculum": [
         {"title": "Ethical Hacking Foundations", "topics": ["Methodologies", "Legal aspects", "Reconnaissance", "Scanning"], "hours": 10},
         {"title": "Network Hacking", "topics": ["Network scanning", "Enumeration", "Sniffing", "MITM attacks", "Password cracking"], "hours": 12},
         {"title": "Web Application Hacking", "topics": ["OWASP Top 10", "SQL Injection", "XSS", "CSRF", "Authentication bypass"], "hours": 14},
         {"title": "System Hacking", "topics": ["Privilege escalation", "Maintaining access", "Clearing tracks", "Malware basics"], "hours": 10},
         {"title": "Advanced Topics", "topics": ["Wireless hacking", "Social engineering", "Cloud security", "Report writing"], "hours": 8},
         {"title": "Projects", "topics": ["Full penetration test", "Web app assessment", "Network assessment"], "hours": 6},
     ]},
    {"title": "Cybersecurity Analyst (SOC)", "slug": "cybersecurity-analyst-soc",
     "category_slug": "cybersecurity", "short_description": "Become a SOC analyst — SIEM, incident response, threat hunting.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 20000, "discount_price": 15999,
     "highlights": ["SOC operations", "SIEM (Splunk/ELK)", "Incident response", "Threat intelligence", "Malware analysis"],
     "tools_covered": ["Splunk", "ELK Stack", "MITRE ATT&CK", "Snort", "Wireshark"],
     "curriculum": [
         {"title": "SOC Fundamentals", "topics": ["SOC roles", "Security frameworks", "NIST", "MITRE ATT&CK", "Kill chain"], "hours": 8},
         {"title": "SIEM", "topics": ["Splunk setup", "Log analysis", "Correlation rules", "Dashboards", "ELK Stack"], "hours": 12},
         {"title": "Incident Response", "topics": ["IR process", "Triage", "Containment", "Eradication", "Recovery"], "hours": 10},
         {"title": "Threat Hunting", "topics": ["Threat intelligence", "IOCs", "Hunting methodologies", "Behavioral analysis"], "hours": 10},
         {"title": "Advanced", "topics": ["Malware analysis", "Forensics intro", "SOC automation", "Project"], "hours": 10},
     ]},
    # Data Engineering
    {"title": "Data Engineering with Python", "slug": "data-engineering-python",
     "category_slug": "data-engineering", "short_description": "Build data pipelines — ETL, Spark, Kafka, Airflow.",
     "level": "intermediate", "duration_hours": 70, "duration_weeks": 10, "price": 25000, "discount_price": 19999,
     "is_featured": True,
     "highlights": ["ETL pipeline development", "Apache Spark", "Apache Kafka", "Apache Airflow", "Data lake & warehouse"],
     "tools_covered": ["Python", "Apache Spark", "Kafka", "Airflow", "dbt", "Snowflake"],
     "curriculum": [
         {"title": "Data Engineering Foundations", "topics": ["Role", "Data architectures", "Batch vs Streaming", "Data quality"], "hours": 6},
         {"title": "SQL & Database Design", "topics": ["Advanced SQL", "Data modeling", "Star/Snowflake schema", "Indexing"], "hours": 10},
         {"title": "Apache Spark", "topics": ["Architecture", "RDDs", "DataFrames", "Spark SQL", "PySpark", "Streaming"], "hours": 14},
         {"title": "Data Pipelines", "topics": ["ETL", "Apache Airflow", "DAGs", "Operators", "dbt"], "hours": 12},
         {"title": "Streaming", "topics": ["Apache Kafka", "Producers & Consumers", "Kafka Streams", "Event-driven"], "hours": 10},
         {"title": "Cloud Data Engineering", "topics": ["AWS Glue", "Redshift/Snowflake", "Data lake", "Delta Lake"], "hours": 10},
         {"title": "Project", "topics": ["End-to-end data pipeline"], "hours": 8},
     ]},
    {"title": "SQL & Database Administration", "slug": "sql-database-admin",
     "category_slug": "data-engineering", "short_description": "Master SQL — PostgreSQL, MySQL, optimization, administration.",
     "level": "beginner", "duration_hours": 40, "duration_weeks": 5, "price": 12000, "discount_price": 8999,
     "highlights": ["SQL from scratch", "PostgreSQL & MySQL", "Query optimization", "Database design", "Administration"],
     "tools_covered": ["PostgreSQL", "MySQL", "pgAdmin", "MySQL Workbench"],
     "curriculum": [
         {"title": "SQL Basics", "topics": ["SELECT", "WHERE", "JOINs", "GROUP BY", "ORDER BY", "Subqueries"], "hours": 8},
         {"title": "Advanced SQL", "topics": ["Window functions", "CTEs", "Recursive queries", "Pivot", "JSON"], "hours": 8},
         {"title": "Database Design", "topics": ["Normalization", "ER modeling", "Keys & Constraints", "Indexing"], "hours": 8},
         {"title": "Performance Tuning", "topics": ["EXPLAIN plans", "Index optimization", "Query rewriting", "Partitioning"], "hours": 8},
         {"title": "Administration", "topics": ["Backup & Recovery", "User management", "Replication", "Security"], "hours": 8},
     ]},
    # DevOps & QA
    {"title": "Selenium Automation Testing", "slug": "selenium-automation-testing",
     "category_slug": "devops-qa", "short_description": "Master Selenium WebDriver — TestNG, Page Object Model, CI/CD.",
     "level": "intermediate", "duration_hours": 50, "duration_weeks": 7, "price": 15000, "discount_price": 11999,
     "is_featured": True,
     "highlights": ["Selenium WebDriver", "TestNG/PyTest", "Page Object Model", "BDD with Cucumber", "CI/CD"],
     "tools_covered": ["Selenium", "Java/Python", "TestNG", "Cucumber", "Jenkins", "Allure"],
     "curriculum": [
         {"title": "Testing Foundations", "topics": ["Manual vs Automation", "Test planning", "Bug lifecycle", "STLC"], "hours": 6},
         {"title": "Selenium WebDriver", "topics": ["Setup", "Locators", "Actions", "Waits", "Frames & Windows"], "hours": 12},
         {"title": "Frameworks", "topics": ["TestNG/PyTest", "Page Object Model", "Data-driven testing"], "hours": 10},
         {"title": "BDD & Cucumber", "topics": ["Gherkin syntax", "Step definitions", "Scenario outline", "Reporting"], "hours": 8},
         {"title": "Advanced", "topics": ["Selenium Grid", "Docker integration", "CI/CD (Jenkins)", "API testing"], "hours": 8},
         {"title": "Projects", "topics": ["E-commerce test suite", "Banking app testing", "CI/CD pipeline"], "hours": 6},
     ]},
    {"title": "API Testing with Postman & REST Assured", "slug": "api-testing",
     "category_slug": "devops-qa", "short_description": "Master API testing — Postman, REST Assured, automation.",
     "level": "intermediate", "duration_hours": 40, "duration_weeks": 5, "price": 12000, "discount_price": 8999,
     "highlights": ["Postman mastery", "REST Assured (Java)", "Newman CLI", "API automation", "Security testing"],
     "tools_covered": ["Postman", "REST Assured", "Newman", "Swagger", "JMeter"],
     "curriculum": [
         {"title": "API Fundamentals", "topics": ["REST architecture", "HTTP methods", "Status codes", "Authentication"], "hours": 6},
         {"title": "Postman", "topics": ["Collections", "Variables", "Scripts", "Newman CLI", "Mock servers"], "hours": 10},
         {"title": "REST Assured", "topics": ["Setup", "GET/POST/PUT/DELETE", "JSON/XML Path", "Authentication"], "hours": 10},
         {"title": "API Automation", "topics": ["Test framework design", "Data-driven testing", "CI/CD", "Reporting"], "hours": 8},
         {"title": "Advanced", "topics": ["OAuth 2.0", "GraphQL testing", "Performance (JMeter)", "Contract testing"], "hours": 6},
     ]},
    # Digital Marketing
    {"title": "Digital Marketing Complete Course", "slug": "digital-marketing",
     "category_slug": "digital-marketing", "short_description": "Complete digital marketing — SEO, SEM, social media, analytics.",
     "level": "beginner", "duration_hours": 60, "duration_weeks": 8, "price": 15000, "discount_price": 11999,
     "is_featured": True,
     "highlights": ["SEO mastery", "Google Ads & SEM", "Social media marketing", "Content strategy", "Email marketing", "Google Analytics"],
     "tools_covered": ["Google Analytics", "Google Ads", "SEMrush", "Ahrefs", "Canva", "Mailchimp"],
     "curriculum": [
         {"title": "Digital Marketing Foundations", "topics": ["Landscape", "Marketing funnel", "Customer journey", "Strategy"], "hours": 6},
         {"title": "SEO", "topics": ["On-page", "Off-page", "Technical SEO", "Keyword research", "Link building"], "hours": 12},
         {"title": "SEM & Google Ads", "topics": ["Google Ads setup", "Campaign types", "Keyword targeting", "Bidding"], "hours": 10},
         {"title": "Social Media Marketing", "topics": ["Facebook/Instagram", "LinkedIn", "YouTube", "Content calendar", "Paid social"], "hours": 10},
         {"title": "Content & Email Marketing", "topics": ["Content strategy", "Blog writing", "Email campaigns", "Automation", "A/B testing"], "hours": 10},
         {"title": "Analytics & Project", "topics": ["Google Analytics 4", "Conversion tracking", "Reports", "ROI measurement", "Portfolio"], "hours": 12},
     ]},
]

MENTORS = [
    {"name": "Dr. Rajesh Kumar", "slug": "dr-rajesh-kumar", "title": "AI & ML Lead Instructor",
     "bio": "PhD in AI from IIT Delhi with 15+ years of industry experience. Former data scientist at Google and Microsoft. Published 30+ research papers in top AI conferences.",
     "experience_years": 15, "specializations": ["AI", "Machine Learning", "Deep Learning", "NLP"]},
    {"name": "Priya Sharma", "slug": "priya-sharma", "title": "Senior SAP Consultant",
     "bio": "SAP Certified Professional with 12+ years in SAP implementations across Fortune 500 companies. Expert in Commerce Cloud, S/4HANA, and CPI.",
     "experience_years": 12, "specializations": ["SAP Commerce Cloud", "SAP S/4HANA", "SAP CPI", "SAP Hybris"]},
    {"name": "Arun Patel", "slug": "arun-patel", "title": "Full Stack Architect",
     "bio": "Senior architect with 14+ years of experience building enterprise-scale applications. Expert in Python, Java, and cloud-native architectures.",
     "experience_years": 14, "specializations": ["Python", "Java", "Microservices", "System Design"]},
    {"name": "Sneha Reddy", "slug": "sneha-reddy", "title": "Cloud & DevOps Expert",
     "bio": "AWS Solutions Architect Professional & Azure Solutions Architect Expert with 10+ years. Led cloud migrations for 50+ enterprises.",
     "experience_years": 10, "specializations": ["AWS", "Azure", "Kubernetes", "Terraform", "DevOps"]},
    {"name": "Vikram Singh", "slug": "vikram-singh", "title": "Cybersecurity Specialist",
     "bio": "CEH, OSCP certified with 11+ years in cybersecurity. Former security analyst at Deloitte. Expert in penetration testing and SOC operations.",
     "experience_years": 11, "specializations": ["Ethical Hacking", "Penetration Testing", "SOC", "Incident Response"]},
    {"name": "Anita Desai", "slug": "anita-desai", "title": "Data Engineering Lead",
     "bio": "Principal data engineer with 13+ years of experience building data platforms at scale. Expert in Spark, Kafka, and cloud data services.",
     "experience_years": 13, "specializations": ["Apache Spark", "Kafka", "Airflow", "Data Warehousing"]},
    {"name": "Karthik Rajan", "slug": "karthik-rajan", "title": "Gen AI & LLM Specialist",
     "bio": "AI researcher and practitioner with 8+ years. Building production LLM applications and agentic AI systems. Active contributor to open-source AI projects.",
     "experience_years": 8, "specializations": ["Generative AI", "LangChain", "RAG", "Agentic AI", "Fine-tuning"]},
    {"name": "Meera Nair", "slug": "meera-nair", "title": "Frontend & React Expert",
     "bio": "Senior frontend engineer with 10+ years of experience. Expert in React ecosystem, Angular, and modern web technologies. Tech lead at multiple startups.",
     "experience_years": 10, "specializations": ["React", "Angular", "Next.js", "TypeScript", "UI/UX"]},
]


class Command(BaseCommand):
    help = 'Seed all categories, courses, and mentors'

    def handle(self, *args, **options):
        self.stdout.write('Seeding categories...')
        for cat_data in CATEGORIES:
            Category.objects.update_or_create(slug=cat_data['slug'], defaults=cat_data)
        self.stdout.write(self.style.SUCCESS(f'Created {len(CATEGORIES)} categories'))

        self.stdout.write('Seeding mentors...')
        for mentor_data in MENTORS:
            Mentor.objects.update_or_create(slug=mentor_data['slug'], defaults=mentor_data)
        self.stdout.write(self.style.SUCCESS(f'Created {len(MENTORS)} mentors'))

        self.stdout.write('Seeding courses...')
        mentors = list(Mentor.objects.all())
        for i, course_data in enumerate(COURSES):
            curriculum = course_data.pop('curriculum', [])
            category_slug = course_data.pop('category_slug')
            category = Category.objects.get(slug=category_slug)

            course, created = Course.objects.update_or_create(
                slug=course_data['slug'],
                defaults={
                    **course_data,
                    'category': category,
                    'mentor': mentors[i % len(mentors)] if mentors else None,
                    'is_published': True,
                    'description': course_data.get('short_description', '') * 3,
                    'enrollment_count': 100 + (i * 37) % 500,
                    'rating': round(4.2 + (i % 8) * 0.1, 1),
                    'review_count': 10 + (i * 13) % 100,
                }
            )

            for idx, module in enumerate(curriculum):
                CurriculumModule.objects.update_or_create(
                    course=course, order=idx + 1,
                    defaults={
                        'title': module['title'],
                        'topics': module['topics'],
                        'duration_hours': module.get('hours', 0),
                    }
                )

            action = 'Created' if created else 'Updated'
            self.stdout.write(f'  {action}: {course.title}')

        self.stdout.write(self.style.SUCCESS(f'\nTotal courses seeded: {len(COURSES)}'))
